apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd_app
spec:
  containers:
  - name: httpd-container
    image: httpd:latest
    resources:
      limits: 
        memory: 20Mi
        cpu: 100m
      requests:
        memory: 15Mi
        cpu: 100m