apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-xfusion
spec:
  capacity:
    storage: 3Gi 
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/dba"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-xfusion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-xfusion
  labels:
    app: httpd
spec:
  containers:
  - name: container-xfusion
    image: httpd:latest
    volumeMounts:
    - mountPath: "/var/www/html"
      name: pvc-xfusion
  volumes:
  - name: pvc-xfusion
    persistentVolumeClaim:
      claimName: pvc-xfusion
  
---
apiVersion: v1
kind: Service
metadata: 
  name: web-xfusion
spec:
  selector:
    app: httpd
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30008
  type: NodePort