apiVersion: v1
kind: Pod
metadata:
  name: volume-share-devops
spec:
  containers:
  - name: volume-container-devops-1
    image: debian:latest
    command: ["sleep","infinity"]
    volumeMounts:
      - name: volume-share
        mountPath: /tmp/beta
  - name: volume-container-devops-2
    image: debian:latest
    command: ["sleep","infinity"]
    volumeMounts:
      - name: volume-share
        mountPath: /tmp/apps
    
  volumes:
  - name: volume-share
    emptyDir: {}
